config/routes.rb
AngularRails::Application.routes.draw do
  resources :games

  resources :books

  get "git_http/show"
  get "taco_order/edit"
  get "hello_angular/show"

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.all

    respond_to do |format|
      format.html {
        @books_json = @books.map {|b| BookSerializer.new(b).serializable_hash}
        @urls = {
          books: books_path
        }
      }
      format.json { render json: @books, root: false, each_serializer: BookSerializer }
    end
  end

  # GET /books/1
  def show
    respond_to do |format|
      format.html {}
      format.json { render json: @book, root: false }
    end
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html {redirect_to @book, notice: 'Book was successfully created.'}
        format.json { render json: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /books/1
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render json: @book }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { render json: "success" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  def index
    @games = Game.page(params[:page]).per(10)

    respond_to do |format|
      format.html {}
      format.json {
        render json: @games,
        meta: {
          number_of_pages: @games.num_pages,
          current_page: @games.current_page,
          total_count: @games.total_count
        }
       }
    end
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(:name)
    end
end

app/controllers/git_http_controller.rb
class GitHttpController < ApplicationController
  def show
  end
end

app/controllers/hello_angular_controller.rb
class HelloAngularController < ApplicationController
  def show
  end
end

app/controllers/taco_order_controller.rb
class TacoOrderController < ApplicationController
  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div ng-app="AngulaRails"
 ng-controller="BooksController"
 ng-init="getBooks()">
  <div class="row">
    <div class="col-md-6">
      <h2>{{formHeader}}</h2>
      <form ng-submit="save()">
        <div class="form-group">
          <label>Title</label>
          <input type="text" class="form-control" ng-model="book.title" />
        </div>
        <div class="form-group">
          <label>Author</label>
          <input type="text" class="form-control" ng-model="book.author" />
        </div>
        <button class="btn btn-primary">
          Save
        </button>
      </form>

      <h1>Books</h1>
      <ul>
        <li ng-repeat="book in books">
          <div class="btn btn-default" ng-click="edit(book, $index)">
            <%= fa_icon "pencil" %>
          </div>
          <div class="btn btn-default" ng-click="delete(book, $index)">
            <%= fa_icon "trash-o" %>
          </div>
          {{ book.title }} by {{ book.author }}
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div ng-app="AngulaRails" ng-controller="GamesController" ng-init="init()"  <h1>Games</h1>
  <%= link_to 'New Game', new_game_path, class: "btn btn-default" %>

  </br>

  <ul class="pagination">
    <li>
      <a ng-click="setPage(currentPage - 1)">Prev</a>
    </li>
    <li ng-repeat="page in pages" ng-class="{active: currentPage == page}">
      <a ng-click="setPage(page)">{{page}}</a>
    </li>
    <li>
      <a ng-click="setPage(currentPage + 1)">Next</a>
    </li>
  </ul>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="game in games">
        <td>{{ game.name }}</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/git_http/show.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="GitHttpController">
  <div class="col-md-6">
    <h1>Gif $http Example</h1>
    <form ng-submit="search()">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="icon-search"></i>
        </span>
        <input type="text" class="form-control"
          placeholder="search for gifs"
          ng-model="query"
        /input>
      </div>
    </form>

    <div class="spinner-icon" ng-show="loading">
      <%= fa_icon "cog spin" %>
    </div>

    <ul class="list-group">
      <li class="list-group-item" ng-repeat="gif in gifs">
        <img src="{{gif.images.fixed_height.url}}">
      </li>
    </ul>

  </div>
</div>

app/views/hello_angular/show.html.erb
<divclass="row" ng-app="AngulaRails" ng-controller="HelloWorldController">
  <div class="col-md-6">
    <h1>Hello AngularJS</h1>
    <p>
      Type in the input box and watch as AngularJS updates the property through the magic of binding.
    </p>
    <input type="text" class="form-control" ng-model="myText" >
    {{ myText }}
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPEhtml>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Angular-Rails" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-inverse">
      <div class="container">
        <a class="navbar-brand" href="#">Angularails</a>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/taco_order/edit.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="TacoOrderController">
  <div class="col-md-6">
    <h3>Add Taco to Order</h3>
    <form ng-submit="addTaco()">
      <div class="form-group">
        <label for="name">Name your creation</label>
        <input type="text"
          class="form-control"
          placeholder="Super Tasy"
          ng-model="taco.name"
        </input>
      </div>

      <div class="form-group">
        <label for="filling">Select your filling</label>
        <select
          ng-model="taco.filling"
          class="form-control"
          ng-options="filling for filling in fillings">
          <option value="">Pick a filling</option>
        </select>
      </div>

      <div class="form-group">
        <label>Cheese</label>
        <div class="radio" ng-repeat="cheese in cheeses">
          <label>
            <input type="radio"
              value="{{cheese}}"
              name="cheeseType"
              ng-model="taco.cheese"
            </input>
            {{cheese}}
          </label>
        </div>
      </div>

      <div class="form-group">
        <label>Extras</label>
        <div class="checkbox" ng-repeat="extra in extras">
          <label>
            <input type="checkbox"
              ng-model="extra.checked"
            </input>
            {{extra.name}}
          </label>
        </div>
      </div>

      <button class="btn btn-primary">
      Submit
      </button>
    </form>
  </div>

  <div class="col-md-6">
    <h3>Your Order</h3>
    <table class="table">
      <tbody>
        <tr ng-repeat="taco in tacos">
          <td>{{taco.name}}</td>
          <td>{{taco.filling}}</td>
          <td>{{taco.cheese}}</td>
          <td>
            <span ng-repeat="extra in taco.extras">
              {{extra}}
            </span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>